server:
  port: ${PORT_SERVICE}
spring:
  data:
    mongodb:
      port: ${PORT_MONGODB}
      uri: ${URI_MONGODB}
eureka:
  client:
    serviceUrl:
      defaultZone: ${URI_EUREKA}
  instance:
    prefer-ip-address: true
    hostname: localhost