server:
  port: 8081
spring:
  data:
    mongodb:
      port: 27017
      uri: ${URI_MONGODB}
eureka:
  client:
    serviceUrl:
      defaultZone: ${URI_EUREKA}
  instance:
    prefer-ip-address: true
    hostname: localhost