
server:
  port: ${PORT_SERVICE}
spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER-SERVICE/
          predicates:
            - Path=/customer/**,/customerType/**
        - id: product
          uri: lb://PRODUCT-SERVICE/
          predicates:
            - Path=/product/**,/productType/**
        - id: customerProduct
          uri: lb://CUSTOMERPRODUCT-SERVICE/
          predicates:
            - Path=/customerProduct/**
        - id: transaction
          uri: lb://TRANSACTION-SERVICE/
          predicates:
            - Path=/transaction/**,/transactionType/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${URI_EUREKA}
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true
    hostname: ${HOST_NAME}
ribbon:
  eureka:
    enabled: true
